[application]
name = "Prépa+"
default_platform = "android"

[application.icon]
asset = "icons/icon.png"

[bundle]
identifier  = "com.circumpolar.prepaplus"
publisher   = "Noctyris"
icon = [
    "icons/icon.png",
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/icon.ico"
]
category = "Education"
