name: Development Build

on:
  push:
    branches: [dev]
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Flutter doctor (infos build)
        run: flutter doctor -v

      - name: Resolve dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Prepare artifact
        run: cp build/app/outputs/flutter-apk/app-debug.apk prepahub-dev.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: prepahub-dev-apk
          path: prepahub-dev.apk
